# Generated by Django 3.2.11 on 2022-07-27 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='update_at',
        ),
    ]
